spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rediscache?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 3
    timeout: 1000s
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
  cache:
    type: redis

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto  # ID主键自增
      logic-delete-value: 1 # 逻辑已删除值（默认为1）
      logic-not-delete-value: # 0 逻辑未删除值（默认为0）
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.zxl.sb.cache.cacheredis.entity

logging:
  level:
    com:
      zxl:
        sb:
          cache:
            cacheredis:
              mapper: debug
